baseURL = "https://ericmurphy.xyz/"
title = "Eric Murphy"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 10

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 20

  [[menu.main]]
    name = "Uses"
    url = "/uses"
    weight = 30

  [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 40

  [[menu.main]]
    name = "Contact"
    url = "mailto:eric@ericmurphy.xyz"
    weight = 50

  [[menu.main]]
    name = "Donate"
    url = "/donate"
    weight = 60

  [[menu.social]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/ericmurphyxyz"
    weight = 10

  [[menu.social]]
    name = "YouTube"
    pre = "youtube"
    url = "https://youtube.com/@ericmurphyxyz"
    weight = 20

  [[menu.social]]
    name = "RSS Feed"
    pre = "rss"
    url = "/index.xml"
    weight = 30



[markup]
  [markup.highlight]
    style = 'catppuccin-macchiato'