baseURL = "https://ericmurphy.xyz/"
title = "Eric Murphy"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 10

  [[menu.main]]
    name = "Software I Use"
    url = "/uses"
    weight = 20

  [[menu.main]]
    name = "Links"
    url = "/links"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "mailto:eric@ericmurphy.xyz"
    weight = 40
